language: python
sudo: false

cache:
  directories:
    - ~/.cache/pip

services:
- docker

env:
  global:
  - secure: QsF7ignSAbH/WCyO6v9bw1exmCWDQR0DqmHkwJ5swc9N44OOOzbWGsaMSYB5y9h+d70fz4arbxQDhsk2KvX4Zd1/2YIMOrIsbgDYeegpkhVPgyQNPKmVqiX+Tb47t1C/TgkC7A07tiPpuefYcLNMZ8gzz7oKhh1UKapYftqzZ+g=
  - secure: HxjeKWSROBQYy9NuNkgQeaK1ubTF8vH5FcR8nUTSAYxxw/qOzKpqkiq4BcJSRcIwTbkvaBf4MshLGVOxPjMeyJFe06UD/6LvTUGS3bwdya+m0RFjHe5/3wzS8/MxLbTlvgzmuGLLKOsJjXCi9eQQchKfHv+QuhGxhYVLQpnbU9E=
  - secure: Zq0Z2UA2A7/ieXX8XoMweClJTp8hiVBxoQ1ylJYNd7qsRSk0QvZhn62db5/x48L9S1kELk0sG64q5Pf96/RPLpdjkBUAdEkS7qF+QOvRvAv2woNEHutjlMUvP6jwYGbug+AORg76btZ57OwMOi3aTkagQMMKnokfo7KGbffy0Jo=
  - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
  - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

before_install:
  - pip install -U pip
  - pip install wheel


install:
  - pip wheel -r requirements-dev.txt
  - pip install -r requirements-dev.txt
  - pip install -e .


script:
- nosetests

deploy:
  provider: pypi
  user: devseed
  password:
    secure: WtawFW/999XYszmZfj1Qk82l00OSyP2JBVOOGCERrW1gVO7MYtYsgP31HKRSzNTCTHJNVDpdK4WZWY6zPQqC3l2UfWYYsvRn0hCoI8AJxE5VCUEg6Ccpe6fMJuhp1pq6Zy7yrfBSZcOB9aqSHLBJsunD2o3mNlTC8WV8vNK74ck=
  on:
    repo: developmentseed/landsat-util
    branch:
      - master

after_deploy:
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "Start Docker Hub Push"
    VER=$(docker run --rm -it -v "$(pwd)":/test -w /test developmentseed/landsat-util:travis python landsat/landsat.py --version | sed s/[^0-9\.]//g)
    docker build . -t developmentseed/landsat-util:$VER
    docker push developmentseed/landsat-util:$VER
  fi
